name: iperf build for Windows
on:
  workflow_dispatch:
  release:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      VERSION: 3.16

    steps:
      - name: Set msys shell
        uses: msys2/setup-msys2@v2.22.0
        with:
          msystem: MSYS
          update: true
          install: make gcc zip git curl

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout iperf repo
        uses: actions/checkout@v4
        with:
          repository: esnet/iperf
          path: iperf
          ref: ${{ env.VERSION }}
          fetch-depth: 0
      
      - name: Build
        id: build
        run: |
          cd ./iperf
          git checkout ${{ env.VERSION }}
          ./configure
          make
          name=iperf-${{ env.VERSION }}
          mkdir $name
          cp src/iperf3.exe $name/iperf.exe
          cp /usr/bin/msys-2.0.dll $name/msys-2.0.dll
          cp LICENSE $name/LICENSE
          zip -r $name.zip $name/
          tar -zcvf $name.tar.gz $name/

      - name: Release
        id: release
        uses: ncipollo/release-action@v1.14.0
        if: steps.build.outcome == 'success'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          tag: ${{ env.VERSION }}
          artifacts: "iperf/iperf-${{ env.VERSION }}.zip,.iperf/iperf-${{ env.VERSION }}.tar.gz"
          commit: ${{ env.VERSION }}
