name: iperf build for Windows
on:
  workflow_dispatch:
  release:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    env:
      tag: '3.16'

    steps:
      - name: Set msys shell
        uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: make gcc zip git curl

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set output
        id: vars
        run: |
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $tag
      - name: Checkout iperf repo
        uses: actions/checkout@v3
        with:
          repository: esnet/iperf
          path: iperf
          ref: "${{ env.tag }}"
          fetch-depth: 0
      
      - name: Build
        id: build
        run: |
          cd ./iperf
          git checkout ${{ env.tag }}
          ./configure
          make
          name=iperf-${{ env.tag }}
          mkdir $name
          cp src/iperf3.exe $name/iperf.exe
          cp /usr/bin/msys-2.0.dll $name/msys-2.0.dll
          cp LICENSE $name/LICENSE
          zip -r $name.zip $name/
          tar -zcvf $name.tar.gz $name/

      - name: Release
        id: release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: steps.build.outcome == 'success'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          automatic_release_tag: "${{ env.tag }}"
          files: |
            ./iperf/iperf-${{ env.tag }}.zip
            ./iperf/iperf-${{ env.tag }}.tar.gz
